source 'https://supermarket.chef.io'

metadata
cookbook 'selinux', '~> 0.9.0'
cookbook 'firewall', '~> 2.4.0'
cookbook 'vim', '~> 2.0.1'
# cookbook 'apache2', '~>3.2.2'
cookbook 'apache2', '~>3.3.0'
cookbook 'mysql', '~> 7.0.0'
cookbook 'php', '~> 1.10.1'
cookbook 'composer', '~> 2.3.0'
cookbook 'phpunit', '~> 1.0.2'
cookbook 'xdebug', '~> 1.0.0'