source 'https://supermarket.chef.io'

metadata
cookbook 'selinux', '~> 2.1.1'
cookbook 'firewall', '~> 2.6.5'
cookbook 'vim', '~> 2.0.2'
cookbook 'java', '~> 2.2.0'
cookbook 'apache2', '~> 5.0.1'
cookbook 'hostsfile', '~> 3.0.1'
# cookbook 'mysql', '~> 8.5.1'
cookbook 'composer', '~> 2.6.1'
cookbook 'phpunit', '~> 1.1.0'
cookbook 'mariadb', '~> 1.5.3'