name 'lms_dev'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lms_dev'
long_description 'Installs/Configures lms_dev'
version '0.1.0'

depends 'selinux', '~> 0.9.0'
depends 'firewall', '~> 2.4.0'
# depends 'vim', '~> 2.0.1'
# depends 'java', '~> 1.50.0'
depends 'apache2', '~>3.3.0'
depends 'hostsfile', '~>0.1.1'
depends 'mysql', '~> 7.0.0'
depends 'composer', '~> 2.6.1'
depends 'phpunit', '~> 1.0.2'
depends 'xdebug', '~> 1.0.0'
depends 'nodejs', '~> 5.0.0'
depends 'htpasswd', '~> 0.3.0'
