name 'lms_dev'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lms_dev'
long_description 'Installs/Configures lms_dev'
version '1.0.0'

depends 'selinux', '~> 2.1.1'
depends 'firewall', '~> 2.6.5'
depends 'vim', '~> 2.0.2'
depends 'java', '~> 3.1.0'
depends 'apache2', '~> 5.0.1'
depends 'hostsfile', '~> 3.0.1'
# depends 'mysql', '~> 8.5.1'
depends 'composer', '~> 2.6.1'
depends 'phpunit', '~> 1.1.0'
depends 'mariadb', '~> 1.5.3'
depends 'ssl_certificate', '~> 2.1.0'